import type { ComponentPreset } from "../types.js";

export const buttonPreset: ComponentPreset = {
  description: "A clickable button component that triggers an action",
  category: "actions",
  complexity: "moderate",
  props: [
    { name: "variant", type: "string", required: false, description: "Visual style variant" },
    { name: "size", type: "string", required: false, default: "md", description: "Button size" },
    {
      name: "disabled",
      type: "boolean",
      required: false,
      default: false,
      description: "Whether the button is disabled",
    },
    {
      name: "loading",
      type: "boolean",
      required: false,
      default: false,
      description: "Whether the button shows a loading state",
    },
    {
      name: "type",
      type: "string",
      required: false,
      default: "button",
      description: "HTML button type attribute",
    },
    { name: "children", type: "ReactNode", required: true, description: "Button content" },
  ],
  variants: [
    {
      name: "variant",
      values: ["primary", "secondary", "outline", "ghost", "destructive"],
      description: "Visual style of the button",
    },
    {
      name: "size",
      values: ["sm", "md", "lg"],
      description: "Size of the button",
    },
  ],
  defaultVariants: { variant: "primary", size: "md" },
  slots: [],
  anatomy: [
    { name: "root", description: "The button element", required: true },
    { name: "label", description: "Text content area", required: true },
    { name: "icon", description: "Optional icon slot", required: false },
    { name: "spinner", description: "Loading spinner overlay", required: false },
  ],
  tokenMapping: {
    "root.background": "{color.primary}",
    "root.background:hover": "{color.primary.hover}",
    "root.background:active": "{color.primary.active}",
    "root.background:disabled": "{color.muted}",
    "root.background[variant=secondary]": "{color.secondary}",
    "root.background[variant=destructive]": "{color.destructive}",
    "root.background[variant=ghost]": "{color.transparent}",
    "root.background[variant=outline]": "{color.transparent}",
    "root.borderColor[variant=outline]": "{color.border}",
    "root.paddingInline[size=sm]": "{spacing.sm}",
    "root.paddingInline[size=md]": "{spacing.md}",
    "root.paddingInline[size=lg]": "{spacing.lg}",
    "root.borderRadius": "{borderRadius.md}",
    "label.color": "{color.primary.foreground}",
    "label.fontFamily": "{fontFamily.sans}",
    "label.fontSize[size=sm]": "{fontSize.sm}",
    "label.fontSize[size=md]": "{fontSize.base}",
    "label.fontSize[size=lg]": "{fontSize.lg}",
  },
  states: ["hover", "focus", "active", "disabled", "loading"],
  events: [
    { name: "onClick", description: "Fired when the button is clicked" },
    { name: "onFocus", description: "Fired when the button receives focus" },
    { name: "onBlur", description: "Fired when the button loses focus" },
  ],
  dependencies: [],
  accessibility: {
    role: "button",
    ariaAttributes: ["aria-disabled", "aria-pressed", "aria-busy"],
    keyboardInteractions: [
      { key: "Enter", description: "Activates the button" },
      { key: "Space", description: "Activates the button" },
    ],
  },
  guidelines: [
    "Use primary variant for the main call-to-action",
    "Use destructive variant for dangerous or irreversible actions",
    "Always provide descriptive text content for screen readers",
    "Disable the button when the action is not available",
    "Show loading state when an async action is in progress",
  ],
};
