import type { ComponentPreset } from "../types.js";

export const inputPreset: ComponentPreset = {
  description: "A text input field for user data entry",
  category: "forms",
  complexity: "moderate",
  props: [
    {
      name: "type",
      type: "string",
      required: false,
      default: "text",
      description: "Input type (text, email, password, number, etc.)",
    },
    { name: "placeholder", type: "string", required: false, description: "Placeholder text" },
    { name: "value", type: "string", required: false, description: "Controlled value" },
    {
      name: "defaultValue",
      type: "string",
      required: false,
      description: "Default value for uncontrolled usage",
    },
    {
      name: "disabled",
      type: "boolean",
      required: false,
      default: false,
      description: "Whether the input is disabled",
    },
    {
      name: "required",
      type: "boolean",
      required: false,
      default: false,
      description: "Whether the input is required",
    },
    { name: "error", type: "string", required: false, description: "Error message to display" },
    { name: "label", type: "string", required: false, description: "Associated label text" },
  ],
  variants: [{ name: "size", values: ["sm", "md", "lg"], description: "Input size" }],
  defaultVariants: { size: "md" },
  slots: [],
  anatomy: [
    { name: "root", description: "Wrapper container", required: true },
    { name: "label", description: "Label element", required: false },
    { name: "input", description: "The input element", required: true },
    { name: "error", description: "Error message container", required: false },
  ],
  tokenMapping: {
    "input.background": "{color.background}",
    "input.borderColor": "{color.border}",
    "input.borderColor:focus": "{color.primary}",
    "input.borderColor:invalid": "{color.destructive}",
    "input.borderColor:disabled": "{color.muted}",
    "input.color": "{color.foreground}",
    "input.color:disabled": "{color.muted.foreground}",
    "input.paddingInline[size=sm]": "{spacing.sm}",
    "input.paddingInline[size=md]": "{spacing.md}",
    "input.borderRadius": "{borderRadius.md}",
    "input.fontFamily": "{fontFamily.sans}",
    "input.fontSize[size=sm]": "{fontSize.sm}",
    "input.fontSize[size=md]": "{fontSize.base}",
    "input.fontSize[size=lg]": "{fontSize.lg}",
    "label.color": "{color.foreground}",
    "label.fontFamily": "{fontFamily.sans}",
    "error.color": "{color.destructive}",
  },
  states: ["hover", "focus", "disabled", "invalid"],
  events: [
    { name: "onChange", description: "Fired when the input value changes" },
    { name: "onFocus", description: "Fired when the input receives focus" },
    { name: "onBlur", description: "Fired when the input loses focus" },
  ],
  dependencies: [],
  accessibility: {
    ariaAttributes: ["aria-invalid", "aria-required", "aria-describedby", "aria-label"],
    keyboardInteractions: [{ key: "Tab", description: "Moves focus to/from the input" }],
  },
  guidelines: [
    "Always associate a label with the input using htmlFor/id",
    "Display validation errors below the input with aria-describedby",
    "Use the appropriate input type for the data being collected",
  ],
};
