import type { ComponentPreset } from "../types.js";

export const selectPreset: ComponentPreset = {
  description: "A dropdown select component for choosing from a list of options",
  category: "forms",
  complexity: "complex",
  props: [
    { name: "value", type: "string", required: false, description: "Currently selected value" },
    {
      name: "defaultValue",
      type: "string",
      required: false,
      description: "Default selected value",
    },
    {
      name: "placeholder",
      type: "string",
      required: false,
      description: "Placeholder text when no option is selected",
    },
    {
      name: "disabled",
      type: "boolean",
      required: false,
      default: false,
      description: "Whether the select is disabled",
    },
    {
      name: "required",
      type: "boolean",
      required: false,
      default: false,
      description: "Whether selection is required",
    },
    {
      name: "options",
      type: "Array<{ label: string; value: string }>",
      required: true,
      description: "List of selectable options",
    },
    { name: "label", type: "string", required: false, description: "Associated label text" },
    { name: "error", type: "string", required: false, description: "Error message to display" },
  ],
  variants: [{ name: "size", values: ["sm", "md", "lg"], description: "Select size" }],
  defaultVariants: { size: "md" },
  slots: [],
  anatomy: [
    { name: "root", description: "Wrapper container", required: true },
    { name: "trigger", description: "The clickable trigger element", required: true },
    { name: "content", description: "Dropdown content container", required: true },
    { name: "option", description: "Individual option element", required: true },
    { name: "label", description: "Label element", required: false },
    { name: "error", description: "Error message container", required: false },
  ],
  tokenMapping: {
    "trigger.background": "{color.background}",
    "trigger.borderColor": "{color.border}",
    "trigger.borderColor:focus": "{color.primary}",
    "trigger.borderColor:invalid": "{color.destructive}",
    "trigger.borderColor:disabled": "{color.muted}",
    "trigger.color": "{color.foreground}",
    "trigger.paddingInline[size=sm]": "{spacing.sm}",
    "trigger.paddingInline[size=md]": "{spacing.md}",
    "trigger.borderRadius": "{borderRadius.md}",
    "trigger.fontFamily": "{fontFamily.sans}",
    "content.background": "{color.popover}",
    "content.borderColor": "{color.border}",
    "content.borderRadius": "{borderRadius.md}",
    "content.shadow": "{shadow.md}",
    "option.background:hover": "{color.accent}",
    "option.color": "{color.foreground}",
    "label.color": "{color.foreground}",
    "error.color": "{color.destructive}",
  },
  states: ["hover", "focus", "open", "disabled", "invalid"],
  events: [
    { name: "onChange", description: "Fired when the selection changes" },
    { name: "onOpenChange", description: "Fired when the dropdown opens or closes" },
  ],
  dependencies: [],
  accessibility: {
    role: "combobox",
    ariaAttributes: [
      "aria-expanded",
      "aria-haspopup",
      "aria-activedescendant",
      "aria-invalid",
      "aria-required",
      "aria-label",
    ],
    keyboardInteractions: [
      { key: "Enter", description: "Opens the dropdown or selects the focused option" },
      { key: "Space", description: "Opens the dropdown or selects the focused option" },
      { key: "ArrowDown", description: "Moves focus to the next option" },
      { key: "ArrowUp", description: "Moves focus to the previous option" },
      { key: "Escape", description: "Closes the dropdown" },
      { key: "Home", description: "Moves focus to the first option" },
      { key: "End", description: "Moves focus to the last option" },
    ],
  },
  guidelines: [
    "Always provide a label for the select",
    "Use a placeholder to indicate what should be selected",
    "Sort options in a logical order (alphabetical, frequency, or contextual)",
    "Use native select for simple cases, custom select only when needed",
  ],
};
