import type { ComponentPreset } from "../types.js";

export const textareaPreset: ComponentPreset = {
  description: "A multi-line text input field",
  category: "forms",
  complexity: "moderate",
  props: [
    { name: "placeholder", type: "string", required: false, description: "Placeholder text" },
    { name: "value", type: "string", required: false, description: "Controlled value" },
    {
      name: "defaultValue",
      type: "string",
      required: false,
      description: "Default value for uncontrolled usage",
    },
    {
      name: "disabled",
      type: "boolean",
      required: false,
      default: false,
      description: "Whether the textarea is disabled",
    },
    {
      name: "required",
      type: "boolean",
      required: false,
      default: false,
      description: "Whether the textarea is required",
    },
    {
      name: "rows",
      type: "number",
      required: false,
      default: 3,
      description: "Number of visible rows",
    },
    { name: "maxLength", type: "number", required: false, description: "Maximum character count" },
    { name: "error", type: "string", required: false, description: "Error message to display" },
    { name: "label", type: "string", required: false, description: "Associated label text" },
  ],
  variants: [
    { name: "size", values: ["sm", "md", "lg"], description: "Textarea size" },
    {
      name: "resize",
      values: ["none", "vertical", "horizontal", "both"],
      description: "Resize behavior",
    },
  ],
  defaultVariants: { size: "md", resize: "vertical" },
  slots: [],
  anatomy: [
    { name: "root", description: "Wrapper container", required: true },
    { name: "label", description: "Label element", required: false },
    { name: "textarea", description: "The textarea element", required: true },
    { name: "counter", description: "Character counter", required: false },
    { name: "error", description: "Error message container", required: false },
  ],
  tokenMapping: {
    "textarea.background": "{color.background}",
    "textarea.borderColor": "{color.border}",
    "textarea.borderColor:focus": "{color.primary}",
    "textarea.borderColor:invalid": "{color.destructive}",
    "textarea.borderColor:disabled": "{color.muted}",
    "textarea.color": "{color.foreground}",
    "textarea.color:disabled": "{color.muted.foreground}",
    "textarea.paddingInline[size=sm]": "{spacing.sm}",
    "textarea.paddingInline[size=md]": "{spacing.md}",
    "textarea.borderRadius": "{borderRadius.md}",
    "textarea.fontFamily": "{fontFamily.sans}",
    "textarea.fontSize[size=sm]": "{fontSize.sm}",
    "textarea.fontSize[size=md]": "{fontSize.base}",
    "textarea.fontSize[size=lg]": "{fontSize.lg}",
    "label.color": "{color.foreground}",
    "label.fontFamily": "{fontFamily.sans}",
    "counter.color": "{color.muted.foreground}",
    "error.color": "{color.destructive}",
  },
  states: ["hover", "focus", "disabled", "invalid"],
  events: [
    { name: "onChange", description: "Fired when the textarea value changes" },
    { name: "onFocus", description: "Fired when the textarea receives focus" },
    { name: "onBlur", description: "Fired when the textarea loses focus" },
  ],
  dependencies: [],
  accessibility: {
    ariaAttributes: ["aria-invalid", "aria-required", "aria-describedby", "aria-label"],
    keyboardInteractions: [{ key: "Tab", description: "Moves focus to/from the textarea" }],
  },
  guidelines: [
    "Always associate a label with the textarea",
    "Show character count when maxLength is set",
    "Display validation errors below the textarea with aria-describedby",
  ],
};
