import type { TokenGroup } from "../../schemas/design-tokens.js";

export function getDefaultTokens(): TokenGroup {
  return {
    color: {
      $type: "color",
      $description: "Color palette",
      primary: { $value: "#3b82f6", $description: "Primary brand color" },
      secondary: { $value: "#64748b", $description: "Secondary color" },
      destructive: { $value: "#ef4444", $description: "Destructive/danger color" },
      success: { $value: "#22c55e", $description: "Success/positive color" },
      warning: { $value: "#f59e0b", $description: "Warning color" },
      background: { $value: "#ffffff", $description: "Default background" },
      foreground: { $value: "#0f172a", $description: "Default foreground/text" },
      muted: { $value: "#f1f5f9", $description: "Muted background" },
      "muted-foreground": { $value: "#64748b", $description: "Muted foreground/text" },
      border: { $value: "#e2e8f0", $description: "Default border color" },
      ring: { $value: "#3b82f6", $description: "Focus ring color" },
    },
    spacing: {
      $type: "dimension",
      $description: "Spacing scale",
      "0": { $value: "0px" },
      px: { $value: "1px" },
      "0.5": { $value: "0.125rem" },
      "1": { $value: "0.25rem" },
      "2": { $value: "0.5rem" },
      "3": { $value: "0.75rem" },
      "4": { $value: "1rem" },
      "5": { $value: "1.25rem" },
      "6": { $value: "1.5rem" },
      "8": { $value: "2rem" },
      "10": { $value: "2.5rem" },
      "12": { $value: "3rem" },
      "16": { $value: "4rem" },
      "20": { $value: "5rem" },
    },
    fontSize: {
      $type: "dimension",
      $description: "Font size scale",
      xs: { $value: "0.75rem" },
      sm: { $value: "0.875rem" },
      base: { $value: "1rem" },
      lg: { $value: "1.125rem" },
      xl: { $value: "1.25rem" },
      "2xl": { $value: "1.5rem" },
      "3xl": { $value: "1.875rem" },
      "4xl": { $value: "2.25rem" },
    },
    fontFamily: {
      $type: "fontFamily",
      $description: "Font family stacks",
      sans: {
        $value: "ui-sans-serif, system-ui, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji'",
        $description: "Default sans-serif font",
      },
      serif: {
        $value: "ui-serif, Georgia, Cambria, 'Times New Roman', Times, serif",
        $description: "Serif font",
      },
      mono: {
        $value: "ui-monospace, SFMono-Regular, 'SF Mono', Menlo, Consolas, monospace",
        $description: "Monospace font",
      },
    },
    fontWeight: {
      $type: "fontWeight",
      $description: "Font weight scale",
      thin: { $value: 100 },
      light: { $value: 300 },
      normal: { $value: 400 },
      medium: { $value: 500 },
      semibold: { $value: 600 },
      bold: { $value: 700 },
      extrabold: { $value: 800 },
    },
    lineHeight: {
      $type: "number",
      $description: "Line height scale",
      none: { $value: 1 },
      tight: { $value: 1.25 },
      snug: { $value: 1.375 },
      normal: { $value: 1.5 },
      relaxed: { $value: 1.625 },
      loose: { $value: 2 },
    },
    letterSpacing: {
      $type: "dimension",
      $description: "Letter spacing scale",
      tighter: { $value: "-0.05em" },
      tight: { $value: "-0.025em" },
      normal: { $value: "0em" },
      wide: { $value: "0.025em" },
      wider: { $value: "0.05em" },
    },
    borderRadius: {
      $type: "dimension",
      $description: "Border radius scale",
      none: { $value: "0px" },
      sm: { $value: "0.125rem" },
      md: { $value: "0.375rem" },
      lg: { $value: "0.5rem" },
      xl: { $value: "0.75rem" },
      "2xl": { $value: "1rem" },
      full: { $value: "9999px" },
    },
    shadow: {
      $type: "shadow",
      $description: "Box shadow scale",
      sm: {
        $value: {
          offsetX: "0px",
          offsetY: "1px",
          blur: "2px",
          spread: "0px",
          color: "rgba(0,0,0,0.05)",
        },
      },
      md: {
        $value: {
          offsetX: "0px",
          offsetY: "4px",
          blur: "6px",
          spread: "-1px",
          color: "rgba(0,0,0,0.1)",
        },
      },
      lg: {
        $value: {
          offsetX: "0px",
          offsetY: "10px",
          blur: "15px",
          spread: "-3px",
          color: "rgba(0,0,0,0.1)",
        },
      },
      xl: {
        $value: {
          offsetX: "0px",
          offsetY: "20px",
          blur: "25px",
          spread: "-5px",
          color: "rgba(0,0,0,0.1)",
        },
      },
      "2xl": {
        $value: {
          offsetX: "0px",
          offsetY: "25px",
          blur: "50px",
          spread: "-12px",
          color: "rgba(0,0,0,0.25)",
        },
      },
    },
    opacity: {
      $type: "number",
      $description: "Opacity scale",
      "0": { $value: 0 },
      "5": { $value: 0.05 },
      "10": { $value: 0.1 },
      "25": { $value: 0.25 },
      "50": { $value: 0.5 },
      "75": { $value: 0.75 },
      "100": { $value: 1 },
    },
    zIndex: {
      $type: "number",
      $description: "Z-index scale",
      "0": { $value: 0 },
      "10": { $value: 10 },
      "20": { $value: 20 },
      "30": { $value: 30 },
      "40": { $value: 40 },
      "50": { $value: 50 },
    },
    duration: {
      $type: "duration",
      $description: "Animation duration scale",
      "75": { $value: "75ms" },
      "100": { $value: "100ms" },
      "150": { $value: "150ms" },
      "200": { $value: "200ms" },
      "300": { $value: "300ms" },
      "500": { $value: "500ms" },
      "700": { $value: "700ms" },
      "1000": { $value: "1000ms" },
    },
    easing: {
      $type: "cubicBezier",
      $description: "Easing functions",
      linear: { $value: [0, 0, 1, 1] },
      in: { $value: [0.4, 0, 1, 1] },
      out: { $value: [0, 0, 0.2, 1] },
      "in-out": { $value: [0.4, 0, 0.2, 1] },
    },
  };
}
